version: '3'

services:
    nginx:
        image: nginx:1.15-alpine
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        ports:
            - 80:80
            - 443:443
            - 8081:8081
        restart: always
        volumes:
            - ./reverseproxy/nginx:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot

    tmilner:
        depends_on:
            - nginx
        build: .
        image: tmilner
        restart: always

    monzo-customisation:
        depends_on:
            - nginx
        image: monzo-customisation
        restart: always

    certbot:
        image: certbot/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot